name: .NET Core CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.102
    - name: Build Backend
      run: dotnet build -c Release -r linux-x64 SDSetupBackend
    - name: Build Updater
      run: dotnet build -c Release -r linux-x64 SDSetupUpdater
    - name: Build Blazor
      run: dotnet build -c Release SDSetupBlazor
